# Generated by Django 4.1.2 on 2022-10-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0003_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='costo',
        ),
    ]
